### ISSUE TITLE
Вернуть удалённые запросы и тесты

### ISSUE THREAD

**Issue by kystyn** [slmtnm/rzd-analysis#4]
Вернуть запрос к pass.rzd.ru/suggester из прошлых коммитов и адаптировать юнит-тесты на функции к исправленной версии кода

**Comment by slmtnm** [comment]
Вернул фукнцию, запрашивающую код станции по имени
```python
def station_code(station_name: str) -> int:
```

Вернул тесты (только не в unittest, а в pytest) в папке tests.
Запускаются командой
```console
$ pytest
```
