### ISSUE TITLE
Составить список статистик для анализа

### ISSUE THREAD

**Issue by slmtnm** [slmtnm/rzd-analysis#7]
По собираемым данным о маршрутах необходимо:

1. Проанализировать получаемые в формате JSON данные и определить интересующие нас поля. Для примера можно выполнить один запрос на получение билетов между Санкт-Петербургом и Москвой на любой день.
2. Составить список интересных статистик для этих полей, с кратким обоснованием каждой (что она может показывать?).
3. Определить наборы статистик, которые кажутся зависимыми для дальнейшего изучения их корреляции (для поиска "скрытых" зависимостей).

**Comment by kystyn** [comment]
1. Зависимость цены билета от времени до отправления поезда. Ожидается, что данная зависимость выглядит ступенчато, и точки начала очередной ступени -- 90, 60, 45, 30, 15 дней. Также возможны падения цен за 0-7 дней до отправления. Эта зависимость поможет исследовать ценовую политику РЖД, не всегда прозрачную особенно за несколько дней до отправления поезда. Полученные зависимости сортируются по ключу "во сколько раз отличается максимальная и минимальная стоимость за весь период продажи билетов". На выход -- зависимости с номерами 0, N-1, N/2. Зависимости нормируются на максимальную стоимость. Получаем три графика с абсциссой 0..1.

Наибольший интерес представляет динамика изменения цен перед и после новым годом, а также в какой-нибудь обычный день января-февраля. Наиболее интересная динамика изменения цен ожидается за 45-0 дней до поезда.

2. То же самое исследование отдельно для фирменных, нефирменных поездов и Сапсана.

3. Зависимость стоимости километра пути от средней скорости поезда. Лучше производить на маршрутах длиной от 1000 км, и отдельно СПб-Мск (650 км). Интересно сравнить стоимость проезда на поезде с самой высокой стоимостью километра пути и стоимость полёта на самолёте по такому же маршрут (в ручном режиме). Можно исследовать отдельно в диапазоне 90-60, 60-45, 45-30, 30-15, 15-0 дней.
Если несколько поездов имеют одну и ту же среднюю скорость и разную цену, то на итоговом графике цена усредняется.

4. То же самое отдельно для фирменных, нефирменных поездов и Сапсана.

5. Зависимость количества свободных мест от количества дней до отправления. Это исследование поможет определить, с какой вероятностью РЖД прицепляет к поезду дополнительные вагоны в случае нехватки мест. Особенный интерес представляет перед новогодними праздниками. Данный график строится для всех поездов. нормируется на итоговое общее количество мест в поезде. Графики сортируются по итоговому количеству мест в поезде. На выход -- зависимости с номерами 0, N-1, N/2. Получаем три графика с абсциссой 0..1.

Все зависимости строятся отдельно для вагонов типа купе, плацкартный, сидячий, СВ, для каждого доступного дня отправления. Какие графики пойдут в презентацию будем решать уже исходя из полученного материала

**Comment by kystyn** [comment]
Реализован интерфейс для получения указанных графиков в заданную дату отправления
Исследование зависимости стоимости километра пути от средней скорости поезда не производится
